apiVersion: customize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: waed-jury-review
resources:
  - deployment.yaml
configMapGenerator:
  - name: jury-cm
    envs:
      - ./configMapGenerator/cm.env